/**
 * Script para popular o banco com as 100 perguntas do Quiz do Chuco.
 *
 * Uso: npx tsx src/scripts/seed-questions.ts
 *
 * Requer variáveis de ambiente:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY  (bypassa RLS)
 *
 * Alternativa: use o MCP Supabase para inserir via SQL direto.
 */

import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !serviceRoleKey) {
  console.error("Defina NEXT_PUBLIC_SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

interface Question {
  level: number;
  difficulty: string;
  category: string;
  text: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_option: string;
  hint: string;
  feedback_wrong: string;
  is_boss: boolean;
}

const questions: Question[] = [
  // ===== NÍVEL 1 - A Floresta das Letras (easy) =====
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual animal tem o pescoço mais comprido?", option_a: "Elefante", option_b: "Girafa", option_c: "Cobra", option_d: "Tartaruga", correct_option: "B", hint: "Ele vive na savana africana e come folhas de árvores bem altas!", feedback_wrong: "Quase! Pense num animal beeeem alto que come folhas no topo das árvores.", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual animal é conhecido como o melhor amigo do homem?", option_a: "Gato", option_b: "Papagaio", option_c: "Cachorro", option_d: "Hamster", correct_option: "C", hint: "Ele abana o rabinho quando está feliz!", feedback_wrong: "Esse animal é super fiel e adora brincar de buscar bolinha!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Quantas cores tem o arco-íris?", option_a: "5", option_b: "6", option_c: "7", option_d: "8", correct_option: "C", hint: "Vermelho, laranja, amarelo, verde, azul, anil e violeta!", feedback_wrong: "Conte nos dedos: vermelho, laranja, amarelo, verde, azul, anil e violeta!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual é o maior planeta do Sistema Solar?", option_a: "Terra", option_b: "Marte", option_c: "Júpiter", option_d: "Saturno", correct_option: "C", hint: "É um planeta gigante de gás com uma grande mancha vermelha!", feedback_wrong: "Esse planeta é tão grande que caberiam mais de 1000 Terras dentro dele!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "O que a galinha bota?", option_a: "Leite", option_b: "Ovo", option_c: "Lã", option_d: "Mel", correct_option: "B", hint: "Usamos para fazer bolo e omelete!", feedback_wrong: "A galinha cacareja e bota algo redondinho que usamos na cozinha!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual estação do ano vem depois do inverno?", option_a: "Verão", option_b: "Outono", option_c: "Primavera", option_d: "Inverno", correct_option: "C", hint: "É quando as flores começam a nascer!", feedback_wrong: "Depois do frio, as flores começam a aparecer. Que estação será?", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual animal voa e tem penas?", option_a: "Morcego", option_b: "Pássaro", option_c: "Borboleta", option_d: "Abelha", correct_option: "B", hint: "Ele canta de manhã e faz ninho nas árvores!", feedback_wrong: "Pense num bichinho que canta, voa e tem penas coloridas!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual é a cor do céu num dia ensolarado?", option_a: "Verde", option_b: "Amarelo", option_c: "Azul", option_d: "Vermelho", correct_option: "C", hint: "Olhe pela janela num dia bonito!", feedback_wrong: "Num dia de sol, olhe para cima. Qual cor você vê?", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Quantos dedos temos nas duas mãos juntas?", option_a: "5", option_b: "8", option_c: "10", option_d: "12", correct_option: "C", hint: "Conte os dedos de uma mão e multiplique por dois!", feedback_wrong: "Cada mão tem 5 dedos. Agora soma as duas!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual animal é preto e branco e vive na China?", option_a: "Zebra", option_b: "Pinguim", option_c: "Panda", option_d: "Gambá", correct_option: "C", hint: "Ele adora comer bambu o dia inteiro!", feedback_wrong: "Esse bichinho fofo adora bambu e vive nas florestas da China!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual forma geométrica tem 3 lados?", option_a: "Quadrado", option_b: "Círculo", option_c: "Triângulo", option_d: "Retângulo", correct_option: "C", hint: "O nome começa com \"tri\", que significa três!", feedback_wrong: "Tri significa três! Qual forma tem três lados?", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "De onde vem o leite que bebemos?", option_a: "Da galinha", option_b: "Da vaca", option_c: "Do porco", option_d: "Da ovelha", correct_option: "B", hint: "É um animal que faz \"muuu\"!", feedback_wrong: "Pense num animal grande que faz \"muuu\" e vive na fazenda!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual animal carrega a casa nas costas?", option_a: "Formiga", option_b: "Caracol", option_c: "Sapo", option_d: "Lagarto", correct_option: "B", hint: "Ele anda beeeem devagar e deixa um rastro brilhante!", feedback_wrong: "Esse bichinho se esconde dentro da conchinha dele quando tem medo!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual é o resultado de 2 + 3?", option_a: "4", option_b: "5", option_c: "6", option_d: "7", correct_option: "B", hint: "Conte nos dedinhos!", feedback_wrong: "Use os dedos: levante 2 de uma mão e 3 da outra. Quantos tem?", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual planeta é conhecido como Planeta Vermelho?", option_a: "Vênus", option_b: "Júpiter", option_c: "Marte", option_d: "Mercúrio", correct_option: "C", hint: "O nome dele é o mesmo de um deus da guerra romano!", feedback_wrong: "Esse planeta tem uma cor avermelhada e fica pertinho da Terra!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual é o maior animal do mundo?", option_a: "Elefante", option_b: "Baleia-azul", option_c: "Tubarão", option_d: "Dinossauro", correct_option: "B", hint: "Ela vive no oceano e é maior que qualquer animal da terra!", feedback_wrong: "Esse animal vive no mar e pode ter mais de 30 metros!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Quantos dias tem uma semana?", option_a: "5", option_b: "6", option_c: "7", option_d: "8", correct_option: "C", hint: "Domingo, segunda, terça, quarta, quinta, sexta e...", feedback_wrong: "Conte: dom, seg, ter, qua, qui, sex, sáb!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Animais", text: "Qual animal faz \"au au\"?", option_a: "Gato", option_b: "Cachorro", option_c: "Pato", option_d: "Cavalo", correct_option: "B", hint: "Ele é o melhor amigo do ser humano!", feedback_wrong: "Esse bichinho late, abana o rabo e adora carinho!", is_boss: false },
  { level: 1, difficulty: "easy", category: "Conhecimentos Gerais", text: "Qual é a fruta amarela que os macacos adoram?", option_a: "Maçã", option_b: "Uva", option_c: "Banana", option_d: "Morango", correct_option: "C", hint: "Ela tem uma casca que a gente descasca pra comer!", feedback_wrong: "Os macacos adoram essa fruta comprida e amarelinha!", is_boss: false },
  { level: 1, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual é o nome do nosso planeta?", option_a: "Marte", option_b: "Lua", option_c: "Terra", option_d: "Sol", correct_option: "C", hint: "É onde todos nós moramos!", feedback_wrong: "É o planeta azul onde vivemos, cheio de água e vida!", is_boss: true },

  // ===== NÍVEL 2 - O Deserto dos Números (medium) =====
  { level: 2, difficulty: "easy", category: "Conhecimentos Gerais", text: "Quanto é 5 x 3?", option_a: "8", option_b: "15", option_c: "12", option_d: "20", correct_option: "B", hint: "É o mesmo que somar 5 três vezes!", feedback_wrong: "5 + 5 + 5 é igual a... tente de novo!", is_boss: false },
  { level: 2, difficulty: "easy", category: "Conhecimentos Gerais", text: "Quantos meses tem um ano?", option_a: "10", option_b: "11", option_c: "12", option_d: "13", correct_option: "C", hint: "Janeiro é o primeiro e dezembro é o último!", feedback_wrong: "Conte: jan, fev, mar, abr, mai, jun, jul, ago, set, out, nov, dez!", is_boss: false },
  { level: 2, difficulty: "easy", category: "Animais", text: "Qual animal tem 8 pernas?", option_a: "Formiga", option_b: "Aranha", option_c: "Barata", option_d: "Centopeia", correct_option: "B", hint: "Ela faz teias para pegar insetos!", feedback_wrong: "Esse bichinho tece teias e tem 8 perninhas!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual é o continente mais gelado do mundo?", option_a: "África", option_b: "Ásia", option_c: "Antártida", option_d: "Europa", correct_option: "C", hint: "Lá vivem os pinguins!", feedback_wrong: "É um lugar coberto de gelo onde vivem pinguins e focas!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual instrumento musical tem teclas pretas e brancas?", option_a: "Violão", option_b: "Flauta", option_c: "Piano", option_d: "Bateria", correct_option: "C", hint: "Mozart tocava esse instrumento quando era criança!", feedback_wrong: "Tem teclas brancas e pretas e faz sons lindos!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Animais", text: "Qual animal muda de cor para se camuflar?", option_a: "Sapo", option_b: "Camaleão", option_c: "Lagarto", option_d: "Cobra", correct_option: "B", hint: "Ele tem olhos que giram para lados diferentes!", feedback_wrong: "Esse réptil muda de cor para se esconder dos predadores!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual é a língua mais falada no mundo?", option_a: "Português", option_b: "Inglês", option_c: "Mandarim", option_d: "Espanhol", correct_option: "C", hint: "É falada na China, o país mais populoso!", feedback_wrong: "É o idioma da China, onde mora mais de 1 bilhão de pessoas!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Quanto é a metade de 100?", option_a: "25", option_b: "40", option_c: "50", option_d: "75", correct_option: "C", hint: "Divida 100 por 2!", feedback_wrong: "Se você dividir 100 em duas partes iguais, cada parte tem...", is_boss: false },
  { level: 2, difficulty: "medium", category: "Animais", text: "O que as abelhas produzem?", option_a: "Seda", option_b: "Mel", option_c: "Leite", option_d: "Cera apenas", correct_option: "B", hint: "É doce e amarelinho, ótimo no pão!", feedback_wrong: "Essas bichinhas trabalhadoras fazem algo doce e gostoso!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual órgão do corpo humano bombeia o sangue?", option_a: "Pulmão", option_b: "Cérebro", option_c: "Coração", option_d: "Fígado", correct_option: "C", hint: "Faz \"tum tum tum\" no seu peito!", feedback_wrong: "Coloque a mão no peito e sinta ele batendo!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Em que país fica a Torre Eiffel?", option_a: "Inglaterra", option_b: "Itália", option_c: "Espanha", option_d: "França", correct_option: "D", hint: "A capital desse país é Paris!", feedback_wrong: "Essa torre famosa fica em Paris, a cidade luz!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Animais", text: "Qual animal terrestre é o mais rápido?", option_a: "Leão", option_b: "Cavalo", option_c: "Guepardo", option_d: "Avestruz", correct_option: "C", hint: "Ele tem pintinhas e corre a mais de 100 km/h!", feedback_wrong: "Esse felino com pintinhas é o velocista da natureza!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual é o resultado de 12 / 4?", option_a: "2", option_b: "3", option_c: "4", option_d: "6", correct_option: "B", hint: "Divida uma dúzia em 4 grupos iguais!", feedback_wrong: "Se você tem 12 balas e divide igualmente para 4 amigos...", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Quantos lados tem um hexágono?", option_a: "4", option_b: "5", option_c: "6", option_d: "8", correct_option: "C", hint: "\"Hexa\" significa seis em grego!", feedback_wrong: "O nome tem \"hexa\" que significa seis!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Animais", text: "Qual é o único mamífero que voa?", option_a: "Águia", option_b: "Morcego", option_c: "Beija-flor", option_d: "Esquilo-voador", correct_option: "B", hint: "Ele dorme de cabeça para baixo!", feedback_wrong: "Esse bichinho noturno dorme pendurado e é um mamífero!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual é o estado da água quando ela ferve?", option_a: "Sólido", option_b: "Líquido", option_c: "Gasoso", option_d: "Plasma", correct_option: "C", hint: "Quando a água ferve, ela vira fumacinha!", feedback_wrong: "A água quente vira vapor. Isso é o estado...", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual planeta tem anéis ao seu redor?", option_a: "Marte", option_b: "Júpiter", option_c: "Saturno", option_d: "Netuno", correct_option: "C", hint: "Seus anéis são feitos de gelo e rocha!", feedback_wrong: "É famoso pelos lindos anéis que giram ao seu redor!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Animais", text: "Quantas patas tem um inseto?", option_a: "4", option_b: "6", option_c: "8", option_d: "10", correct_option: "B", hint: "Formigas, besouros, abelhas... conte as patinhas!", feedback_wrong: "Todo inseto tem exatamente o mesmo número de pernas!", is_boss: false },
  { level: 2, difficulty: "medium", category: "Conhecimentos Gerais", text: "Qual é a capital do Brasil?", option_a: "São Paulo", option_b: "Rio de Janeiro", option_c: "Brasília", option_d: "Salvador", correct_option: "C", hint: "Foi construída no formato de um avião!", feedback_wrong: "Não é São Paulo nem Rio! É uma cidade planejada no centro do país!", is_boss: false },
  { level: 2, difficulty: "hard", category: "Conhecimentos Gerais", text: "Quanto é 7 x 8?", option_a: "54", option_b: "56", option_c: "48", option_d: "63", correct_option: "B", hint: "7 x 8 é quase 60, mas um pouquinho menos!", feedback_wrong: "Multiplique 7 por 8. Dica: 7x7=49, agora some mais 7!", is_boss: true },

  // ===== NÍVEL 3 - O Oceano Animal (hard, animais) =====
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual é o maior animal terrestre?", option_a: "Rinoceronte", option_b: "Hipopótamo", option_c: "Elefante", option_d: "Girafa", correct_option: "C", hint: "Ele tem uma tromba bem comprida!", feedback_wrong: "Esse grandalhão tem trombinha, orelhas enormes e presas!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual animal marinho tem 8 tentáculos?", option_a: "Lula", option_b: "Polvo", option_c: "Água-viva", option_d: "Estrela-do-mar", correct_option: "B", hint: "Ele é super inteligente e consegue abrir potes!", feedback_wrong: "Esse animal esperto do mar tem 8 bracinhos e pode mudar de cor!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual ave não consegue voar mas nada muito bem?", option_a: "Avestruz", option_b: "Galinha", option_c: "Pinguim", option_d: "Peru", correct_option: "C", hint: "Ele vive em lugares muito frios e anda de forma engraçada!", feedback_wrong: "Essa ave fofa vive no gelo, não voa, mas nada como um campeão!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual animal produz seda?", option_a: "Aranha", option_b: "Bicho-da-seda", option_c: "Abelha", option_d: "Formiga", correct_option: "B", hint: "É uma lagartinha que faz um casulo!", feedback_wrong: "É uma larvinha que tece fios finíssimos para fazer seu casulo!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual é o animal mais venenoso do mundo?", option_a: "Cobra-rei", option_b: "Aranha-marrom", option_c: "Água-viva-caixa", option_d: "Escorpião", correct_option: "C", hint: "Ela vive no oceano e é quase transparente!", feedback_wrong: "Esse animal marinho quase invisível é extremamente perigoso!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Como se chama o filhote do sapo?", option_a: "Sapinho", option_b: "Girino", option_c: "Larvinha", option_d: "Rãzinha", correct_option: "B", hint: "Ele parece um peixinho com rabinho e vive na água!", feedback_wrong: "O bebê do sapo vive na água e tem um rabinho. Depois ele cresce e pula!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual animal é conhecido por ter ótima memória?", option_a: "Golfinho", option_b: "Cachorro", option_c: "Elefante", option_d: "Coruja", correct_option: "C", hint: "Dizem que ele nunca esquece!", feedback_wrong: "Esse grandão de tromba dizem que nunca, nunca esquece nada!", is_boss: false },
  { level: 3, difficulty: "medium", category: "Animais", text: "Qual pássaro é símbolo de sabedoria?", option_a: "Águia", option_b: "Coruja", option_c: "Papagaio", option_d: "Tucano", correct_option: "B", hint: "Ela enxerga bem no escuro e vive à noite!", feedback_wrong: "Esse pássaro noturno é muito associado ao conhecimento!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual animal pode regenerar partes do corpo?", option_a: "Lagarto", option_b: "Estrela-do-mar", option_c: "Salamandra", option_d: "Todos estes", correct_option: "D", hint: "Pense em mais de um animal que tem esse poder!", feedback_wrong: "Na verdade, vários animais têm essa habilidade incrível!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Quantos estômagos tem uma vaca?", option_a: "1", option_b: "2", option_c: "3", option_d: "4", correct_option: "D", hint: "Ela precisa digerir muito capim!", feedback_wrong: "A vaca tem vários estômagos para conseguir digerir o capim!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual é o menor pássaro do mundo?", option_a: "Pardal", option_b: "Beija-flor-abelha", option_c: "Andorinha", option_d: "Canário", correct_option: "B", hint: "Ele é tão pequeno que parece um inseto!", feedback_wrong: "Esse passarinho minúsculo bate as asas super rápido!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual animal dorme em pé?", option_a: "Vaca", option_b: "Cavalo", option_c: "Girafa", option_d: "Todas acima", correct_option: "D", hint: "Vários animais grandes fazem isso!", feedback_wrong: "Vários animais conseguem cochilar sem deitar!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual é o animal mais lento do mundo?", option_a: "Tartaruga", option_b: "Caracol", option_c: "Bicho-preguiça", option_d: "Lesma", correct_option: "C", hint: "Ele vive pendurado nas árvores e se move devagarzinho!", feedback_wrong: "Esse bichinho das árvores se move tão devagar que algas crescem nele!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual peixe pode gerar eletricidade?", option_a: "Tubarão", option_b: "Poraquê", option_c: "Peixe-palhaço", option_d: "Baiacu", correct_option: "B", hint: "Ele vive nos rios da Amazônia!", feedback_wrong: "Esse peixe elétrico da Amazônia pode dar choques bem fortes!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual animal tem a mordida mais forte?", option_a: "Leão", option_b: "Tubarão", option_c: "Crocodilo", option_d: "Hipopótamo", correct_option: "C", hint: "Ele vive em rios e pântanos e é um réptil!", feedback_wrong: "Esse réptil enorme de mandíbulas poderosas vive em rios tropicais!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Quantos corações tem um polvo?", option_a: "1", option_b: "2", option_c: "3", option_d: "4", correct_option: "C", hint: "Ele tem mais corações que os humanos!", feedback_wrong: "O polvo é incrível: tem 3 corações para bombear sangue azul!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual inseto pode carregar 50 vezes o próprio peso?", option_a: "Abelha", option_b: "Formiga", option_c: "Besouro", option_d: "Grilo", correct_option: "B", hint: "Ela trabalha em equipe e vive em colônias!", feedback_wrong: "Essa bichinha pequenininha é super forte para o tamanho dela!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual animal tem impressão digital parecida com a humana?", option_a: "Macaco", option_b: "Gato", option_c: "Coala", option_d: "Gorila", correct_option: "C", hint: "Ele vive na Austrália e come eucalipto!", feedback_wrong: "Esse bichinho australiano fofo tem digitais quase iguais às nossas!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual é o único gato grande que sabe nadar e gosta de água?", option_a: "Leão", option_b: "Tigre", option_c: "Leopardo", option_d: "Pantera", correct_option: "B", hint: "Ele tem listras e vive na Ásia!", feedback_wrong: "Esse felino listrado adora tomar banho nos rios!", is_boss: false },
  { level: 3, difficulty: "hard", category: "Animais", text: "Qual animal terrestre é o mais alto do mundo?", option_a: "Elefante", option_b: "Girafa", option_c: "Urso-polar", option_d: "Alce", correct_option: "B", hint: "Ela pode ter até 6 metros de altura!", feedback_wrong: "Com aquele pescoção, ela alcança as folhas mais altas!", is_boss: true },

  // ===== NÍVEL 4 - A Cidade Tecnológica (hard, tech/ciências) =====
  { level: 4, difficulty: "medium", category: "Tecnologia", text: "O que significa \"www\" na internet?", option_a: "World Wide Web", option_b: "World Wifi Web", option_c: "Web World Wide", option_d: "Wide World Web", correct_option: "A", hint: "É a rede mundial de computadores!", feedback_wrong: "São três palavras em inglês que significam \"Rede Mundial\"!", is_boss: false },
  { level: 4, difficulty: "medium", category: "Tecnologia", text: "Quem inventou a lâmpada elétrica?", option_a: "Albert Einstein", option_b: "Thomas Edison", option_c: "Nikola Tesla", option_d: "Graham Bell", correct_option: "B", hint: "Ele fez mais de mil invenções!", feedback_wrong: "Esse inventor americano fez mais de 1000 invenções, incluindo a lâmpada!", is_boss: false },
  { level: 4, difficulty: "medium", category: "Tecnologia", text: "O que é um robô?", option_a: "Um tipo de computador", option_b: "Uma máquina que faz tarefas", option_c: "Um programa de TV", option_d: "Um brinquedo apenas", correct_option: "B", hint: "Eles podem ser programados para ajudar pessoas!", feedback_wrong: "Robôs são máquinas inteligentes criadas para realizar tarefas!", is_boss: false },
  { level: 4, difficulty: "medium", category: "Ciências", text: "Qual gás as plantas absorvem do ar?", option_a: "Oxigênio", option_b: "Nitrogênio", option_c: "Gás carbônico", option_d: "Hidrogênio", correct_option: "C", hint: "É o gás que nós soltamos quando respiramos!", feedback_wrong: "As plantas respiram o oposto de nós. Elas absorvem o que a gente solta!", is_boss: false },
  { level: 4, difficulty: "medium", category: "Ciências", text: "De que são feitas as nuvens?", option_a: "Algodão", option_b: "Fumaça", option_c: "Gotinhas de água", option_d: "Poeira", correct_option: "C", hint: "Quando chove, de onde vem a água?", feedback_wrong: "As nuvens são formadas por gotinhas minúsculas de água flutuando!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "Qual animal foi o primeiro a ir ao espaço?", option_a: "Cachorro", option_b: "Macaco", option_c: "Mosca-da-fruta", option_d: "Gato", correct_option: "C", hint: "Foram insetos bem pequenos em 1947!", feedback_wrong: "Antes dos cachorros e macacos, insetos bem pequenos foram ao espaço!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "Qual é o osso mais longo do corpo humano?", option_a: "Úmero", option_b: "Tíbia", option_c: "Fêmur", option_d: "Coluna", correct_option: "C", hint: "Fica na sua coxa, a parte de cima da perna!", feedback_wrong: "É o osso da coxa, entre o quadril e o joelho!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "Em que ano o homem pisou na Lua pela primeira vez?", option_a: "1965", option_b: "1969", option_c: "1972", option_d: "1959", correct_option: "B", hint: "Foi no final dos anos 60!", feedback_wrong: "Neil Armstrong pisou na Lua em julho de 1969!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "Qual é o metal mais leve que existe?", option_a: "Alumínio", option_b: "Ferro", option_c: "Lítio", option_d: "Titânio", correct_option: "C", hint: "É usado em baterias de celular!", feedback_wrong: "Esse metal super leve é usado nas baterias dos nossos celulares!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "O que causa o arco-íris?", option_a: "Chuva apenas", option_b: "Luz do sol na chuva", option_c: "Vento forte", option_d: "Nuvens coloridas", correct_option: "B", hint: "Precisa de sol e chuva ao mesmo tempo!", feedback_wrong: "Quando a luz do sol atravessa as gotinhas de chuva, a mágica acontece!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "O que é um pixel?", option_a: "Um tipo de vírus", option_b: "O menor ponto de uma tela", option_c: "Uma marca de celular", option_d: "Um jogo de computador", correct_option: "B", hint: "São milhões deles na tela do seu celular!", feedback_wrong: "Cada pontinho de luz na sua tela é um desses!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "Qual é o planeta mais quente do Sistema Solar?", option_a: "Mercúrio", option_b: "Vênus", option_c: "Marte", option_d: "Júpiter", correct_option: "B", hint: "Não é o mais perto do Sol! O efeito estufa o torna mais quente!", feedback_wrong: "Mesmo não sendo o mais próximo do Sol, esse planeta retém muito calor!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "Qual linguagem os computadores entendem na base?", option_a: "Português", option_b: "Inglês", option_c: "Binário (0 e 1)", option_d: "Emojis", correct_option: "C", hint: "São apenas dois números: zero e um!", feedback_wrong: "Computadores pensam em zeros e uns!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "Quanto tempo a luz do Sol demora para chegar à Terra?", option_a: "1 segundo", option_b: "8 minutos", option_c: "1 hora", option_d: "1 dia", correct_option: "B", hint: "A luz é super rápida, mas o Sol fica longe!", feedback_wrong: "A luz viaja a 300 mil km/s, mas o Sol fica a 150 milhões de km!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "O que é inteligência artificial?", option_a: "Um robô com sentimentos", option_b: "Máquinas que aprendem sozinhas", option_c: "Um cérebro eletrônico", option_d: "Um videogame", correct_option: "B", hint: "ChatGPT e Alexa são exemplos disso!", feedback_wrong: "São programas de computador que podem aprender e tomar decisões!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "Qual é a estrela mais próxima da Terra?", option_a: "Alpha Centauri", option_b: "Sirius", option_c: "O Sol", option_d: "Polaris", correct_option: "C", hint: "Você vê ela todo dia de manhã!", feedback_wrong: "Essa estrela ilumina e aquece nosso planeta todo dia!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "O que é a fotossíntese?", option_a: "Tirar fotos da natureza", option_b: "Como as plantas fazem comida", option_c: "Um tipo de energia", option_d: "Uma reação química no fogo", correct_option: "B", hint: "As plantas usam luz do sol para isso!", feedback_wrong: "É o processo mágico das plantas: usam sol, água e CO2 para fazer alimento!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "Quem criou o Facebook?", option_a: "Bill Gates", option_b: "Steve Jobs", option_c: "Mark Zuckerberg", option_d: "Elon Musk", correct_option: "C", hint: "Ele criou a rede social quando era universitário!", feedback_wrong: "Esse jovem criou a rede social mais famosa quando estava na faculdade!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Ciências", text: "De que material é feito o diamante?", option_a: "Cristal", option_b: "Carbono", option_c: "Vidro", option_d: "Metal", correct_option: "B", hint: "É o mesmo elemento do grafite do lápis!", feedback_wrong: "É feito do mesmo elemento que a pontinha do seu lápis, mas organizado diferente!", is_boss: false },
  { level: 4, difficulty: "hard", category: "Tecnologia", text: "Qual foi o primeiro videogame da história?", option_a: "Pac-Man", option_b: "Pong", option_c: "Mario Bros", option_d: "Tetris", correct_option: "B", hint: "Era um jogo de \"tênis\" com dois risquinhos e uma bolinha!", feedback_wrong: "Era super simples: dois riscos rebatendo uma bolinha, tipo tênis de mesa!", is_boss: true },

  // ===== NÍVEL 5 - O Laboratório Secreto (hard, mix) =====
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Qual é o rio mais longo do mundo?", option_a: "Rio Amazonas", option_b: "Rio Nilo", option_c: "Rio Mississipi", option_d: "Rio Yangtzé", correct_option: "B", hint: "Ele fica na África e passa pelo Egito!", feedback_wrong: "Esse rio enorme atravessa o deserto do Saara e chega ao mar Mediterrâneo!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Qual é o país mais populoso do mundo?", option_a: "Estados Unidos", option_b: "Índia", option_c: "China", option_d: "Brasil", correct_option: "B", hint: "Ultrapassou a China recentemente!", feedback_wrong: "Esse país asiático tem mais de 1,4 bilhão de pessoas!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "O que é um átomo?", option_a: "Um tipo de célula", option_b: "A menor partícula de um elemento", option_c: "Um planeta pequeno", option_d: "Uma molécula de água", correct_option: "B", hint: "Tudo no universo é feito dessas partículas minúsculas!", feedback_wrong: "É a menor partícula que forma toda a matéria do universo!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Quem pintou a Mona Lisa?", option_a: "Pablo Picasso", option_b: "Vincent van Gogh", option_c: "Leonardo da Vinci", option_d: "Michelangelo", correct_option: "C", hint: "Ele também projetou máquinas voadoras há 500 anos!", feedback_wrong: "Esse gênio italiano era pintor, inventor e cientista ao mesmo tempo!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "Qual é a velocidade da luz?", option_a: "300 km/s", option_b: "3.000 km/s", option_c: "30.000 km/s", option_d: "300.000 km/s", correct_option: "D", hint: "É tão rápida que dá 7 voltas na Terra em 1 segundo!", feedback_wrong: "A luz é a coisa mais rápida do universo: 300 mil km por segundo!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Quantos oceanos existem no planeta Terra?", option_a: "3", option_b: "4", option_c: "5", option_d: "7", correct_option: "C", hint: "Pacífico, Atlântico, Índico, Ártico e Antártico!", feedback_wrong: "São 5: Pacífico, Atlântico, Índico, Ártico e Antártico!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "O que é o DNA?", option_a: "Um tipo de vitamina", option_b: "O código genético dos seres vivos", option_c: "Uma doença", option_d: "Um tipo de célula", correct_option: "B", hint: "É como um manual de instruções dentro das nossas células!", feedback_wrong: "É a molécula que carrega todas as instruções para formar um ser vivo!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Qual instrumento mede terremotos?", option_a: "Barômetro", option_b: "Termômetro", option_c: "Sismógrafo", option_d: "Telescópio", correct_option: "C", hint: "O nome tem \"sismo\", que significa tremor!", feedback_wrong: "Sismo = tremor, grafo = escrever. Esse aparelho registra os tremores!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "Qual é o elemento químico mais abundante no universo?", option_a: "Oxigênio", option_b: "Carbono", option_c: "Hélio", option_d: "Hidrogênio", correct_option: "D", hint: "As estrelas são feitas principalmente desse elemento!", feedback_wrong: "É o elemento mais simples e mais abundante. As estrelas brilham por causa dele!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Em que continente fica o Egito?", option_a: "Ásia", option_b: "Europa", option_c: "África", option_d: "Oceania", correct_option: "C", hint: "As pirâmides ficam nesse continente!", feedback_wrong: "O Egito e suas pirâmides ficam no norte da África!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "O que acontece com a água a 0 graus Celsius?", option_a: "Evapora", option_b: "Congela", option_c: "Ferve", option_d: "Nada", correct_option: "B", hint: "Pense no que acontece no congelador!", feedback_wrong: "Quando a temperatura chega a zero, a água vira gelo!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Qual é a montanha mais alta do mundo?", option_a: "Monte Fuji", option_b: "Monte Everest", option_c: "Monte Kilimanjaro", option_d: "Monte Branco", correct_option: "B", hint: "Fica entre o Nepal e a China!", feedback_wrong: "Com 8.849 metros, essa montanha no Himalaia é a mais alta da Terra!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "Quantos planetas tem o Sistema Solar?", option_a: "7", option_b: "8", option_c: "9", option_d: "10", correct_option: "B", hint: "Plutão não conta mais como planeta!", feedback_wrong: "Desde 2006, são 8 planetas. Plutão virou planeta-anão!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Quem escreveu Romeu e Julieta?", option_a: "Charles Dickens", option_b: "William Shakespeare", option_c: "Mark Twain", option_d: "Machado de Assis", correct_option: "B", hint: "Ele é o escritor mais famoso da Inglaterra!", feedback_wrong: "Esse dramaturgo inglês escreveu as peças mais famosas da história!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "O que é a gravidade?", option_a: "Uma força que empurra para cima", option_b: "A força que puxa tudo para o centro da Terra", option_c: "O peso dos objetos", option_d: "A velocidade de queda", correct_option: "B", hint: "É por isso que a maçã cai da árvore!", feedback_wrong: "Newton descobriu essa força quando uma maçã caiu na cabeça dele!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Qual é o esporte mais popular do mundo?", option_a: "Basquete", option_b: "Críquete", option_c: "Futebol", option_d: "Tênis", correct_option: "C", hint: "A Copa do Mundo é o maior evento desse esporte!", feedback_wrong: "Bilhões de pessoas no mundo inteiro torcem nesse esporte com bola nos pés!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "De que gás é feita a maior parte da atmosfera da Terra?", option_a: "Oxigênio", option_b: "Nitrogênio", option_c: "Gás carbônico", option_d: "Hidrogênio", correct_option: "B", hint: "Não é o oxigênio! Ele é só 21% do ar!", feedback_wrong: "Cerca de 78% do ar que respiramos é feito desse gás!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Quantas notas musicais existem?", option_a: "5", option_b: "6", option_c: "7", option_d: "8", correct_option: "C", hint: "Dó, Ré, Mi, Fá, Sol, Lá, Si!", feedback_wrong: "Conte: Dó, Ré, Mi, Fá, Sol, Lá, Si!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Ciências", text: "O que é um fóssil?", option_a: "Uma pedra bonita", option_b: "Restos preservados de seres antigos", option_c: "Um tipo de mineral", option_d: "Uma rocha vulcânica", correct_option: "B", hint: "É assim que sabemos que os dinossauros existiram!", feedback_wrong: "São restos de animais e plantas de milhões de anos, preservados nas rochas!", is_boss: false },
  { level: 5, difficulty: "hard", category: "Conhecimentos Gerais", text: "Se você misturar todas as cores do arco-íris, qual cor aparece?", option_a: "Preto", option_b: "Branco", option_c: "Cinza", option_d: "Marrom", correct_option: "B", hint: "A luz branca contém todas as cores!", feedback_wrong: "Quando toda a luz se junta, ela forma a cor branca! Newton descobriu isso!", is_boss: true },
];

async function seed() {
  console.log(`Inserindo ${questions.length} perguntas...`);

  // Limpa tabela antes de inserir
  const { error: deleteError } = await supabase
    .from("qz_questions")
    .delete()
    .neq("id", 0);

  if (deleteError) {
    console.error("Erro ao limpar tabela:", deleteError);
    process.exit(1);
  }

  const { data, error } = await supabase
    .from("qz_questions")
    .insert(questions)
    .select("id");

  if (error) {
    console.error("Erro ao inserir:", error);
    process.exit(1);
  }

  console.log(`${data.length} perguntas inseridas com sucesso!`);
}

seed();
